### ISSUE TITLE
Great Work !!! Few Queries..

### ISSUE THREAD

**Issue by amandpkr** [MrTornado24/FENeRF#12]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/x_fahkh/.conda/envs/gmpi/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/proj/cvl/users/x_fahkh/mn/debug-dmpi/gmpi/prepsem/Bisnet.py", line 23, in forward
    x = F.relu(self.bn(x))
  File "/home/x_fahkh/.conda/envs/gmpi/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1071, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/x_fahkh/.conda/envs/gmpi/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 178, in forward
    self.eps,
  File "/home/x_fahkh/.conda/envs/gmpi/lib/python3.7/site-packages/torch/nn/functional.py", line 2279, in batch_norm
    _verify_batch_size(input.size())
  File "/home/x_fahkh/.conda/envs/gmpi/lib/python3.7/site-packages/torch/nn/functional.py", line 2247, in _verify_batch_size
    raise ValueError("Expected more than 1 value per channel when training, got input size {}".format(size))
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 128, 1, 1])
```

When I tried to provide the segmentation Map for FFHQ I am getting this error. 

Can you Please have a look at this

**Comment by MrTornado24** [comment]
Hi, what is the command?

**Comment by amandpkr** [comment]
Actual when we are setting the batch size = 1, Then 
https://github.com/MrTornado24/FENeRF/blob/9d90acda243b7c7d7f2c688a3bb333da2e7f8894/generators/BiSeNet.py#L27
is throwing an error because of batch normalization. 
Can't we do this for single images?

**Comment by MrTornado24** [comment]
> Actual when we are setting the batch size = 1, Then
> 
> https://github.com/MrTornado24/FENeRF/blob/9d90acda243b7c7d7f2c688a3bb333da2e7f8894/generators/BiSeNet.py#L27
> 
> 
> is throwing an error because of batch normalization.
> Can't we do this for single images?

Yes, you're right. More than one batch size is expected when processing batch norm. If you want to use only one data point, you can  add `model.eval()` before inputing data.
